Refactored tool stack section.
lambdaclass/lambdaclass_hacking_learning_path pull request #113
Opened 2024-04-15 18:46 UTC by samoht9277

2024-04-15 19:15 UTC, Loco1982 requested changes
Don't forget to put a description to your PR. No PR should be merged if they don't have a description. Thanks!

2024-04-15 19:15 UTC, Loco1982 commented on README.md
> +  - **Notion** helps to document any information worth saving and sharing to the rest of the company.
```suggestion
  - **Notion** helps to document any information worth saving and sharing with your team or the rest of the company.
```

2024-04-15 19:15 UTC, Loco1982 commented on README.md
> +  - **Duo** is our 2FA way of validating your identity. Tasks such as logging into Slack, 1Password or GitHub require you to prove your identity, besides your password.
```suggestion
  - **Duo** is our 2FA way of validating your identity. Tasks such as logging into Slack, 1Password, or GitHub require you to prove your identity, besides your password. 
```

2024-04-15 19:15 UTC, Loco1982 commented on README.md
> +  -  We use **1Password** to store all our secrets and shared passwords. Most projects have a thing called _Vault_, which is a location where you can share secrets and passwords with your team. A per
```suggestion
  -  We use **1Password** to store all our secrets and shared passwords. Most projects have a thing called _Vault_, which is a location where you can share secrets and passwords with your team. A personal subscription is included for you to store your own passwords. The company cannot see nor edit your private account.
```

2024-04-15 19:15 UTC, Loco1982 commented on README.md
> +  - We use **GitHub** to store all our code! This platform let developers contribute to a centralized project, allowing synchronous progress for the project.
```suggestion
  - We use **GitHub** to store all our code! This platform lets developers contribute to a centralized project, allowing synchronous progress for the project.
```

2024-04-15 19:18 UTC, samoht9277 commented on README.md
> +  - We use **GitHub** to store all our code! This platform let developers contribute to a centralized project, allowing synchronous progress for the project.
Nice catches!

2024-04-15 19:20 UTC, Loco1982 approved these changes
LGTM

2024-04-15 20:16 UTC, tomasdema approved these changes
lgtm

2024-04-15 20:33 UTC, fmoletta approved these changes
🚀

2024-04-25 19:37 UTC, klaus993 approved these changes

2024-04-25 19:48 UTC, Loco1982 approved these changes
LGTM

2024-04-25 19:48 UTC, merged