Added EOL resource
lambdaclass/lambdaclass_hacking_learning_path pull request #63
Opened 2022-04-26 20:26 UTC by Loco1982

Added to the git section a link about EOL.

2022-04-26 22:26 UTC, facundoolano approved these changes

2022-05-22 00:27 UTC, juanbono requested changes
It should be 
`Configure your end of line (EOL) management in your development environment`

2022-07-08 21:25 UTC, SantiagoPittella requested changes

2022-07-08 21:25 UTC, SantiagoPittella commented on README.md
> +- [Merging vs Rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing]
At the end of this line we have an `]` but we need an `)`

2022-07-08 21:32 UTC, SantiagoPittella reviewed
fix typo

2022-07-08 21:34 UTC, SantiagoPittella approved these changes

2022-07-08 21:35 UTC, juanbono approved these changes

2022-07-08 21:35 UTC, merged