Update README.md
lambdaclass/lambdaclass_hacking_learning_path pull request #85
Opened 2023-05-16 13:38 UTC by TavoPM29

-Remove a link from the Docker section that was not working
-Remove some titles that did not have any type of information between the Functional Programming and Erlang section.

2023-05-16 13:43 UTC, Loco1982 commented
This PR has things beyond its scope. It deletes placeholder titles when it should only delete the Docker link (the task at hand). It should be modified to stick to the scope of the task.

2023-05-16 13:43 UTC, Loco1982 requested changes

2023-05-16 13:43 UTC, Loco1982 commented on README.md
> -
These titles are placeholders, I wouldn't delete them.

2023-06-09 16:21 UTC, jrchatruc approved these changes

2023-06-09 17:12 UTC, Loco1982 approved these changes
LGTM

2023-06-09 17:12 UTC, merged