Added other examples of project management software
lambdaclass/lambdaclass_hacking_learning_path pull request #90
Opened 2023-06-14 15:09 UTC by Loco1982

We don't use only clickup

2023-06-14 15:19 UTC, matias-gonz approved these changes
I left a suggestion but it is not a big deal

2023-06-14 15:19 UTC, matias-gonz commented on README.md
> +- When working on projects, the specific tasks to tackle are written in tickets on a project management software (i.e. Clickup, Trello, Jira, or Github Projects).
```suggestion
- When working on projects, the specific tasks to tackle are written in tickets on some project management software (i.e. Clickup, Trello, Jira, or Github Projects).
```

2023-06-14 15:19 UTC, tomasdema requested changes
I would say our standard tool is Github Projects but we have some legacy tools like clickup, trello etc. If we have a new project we should use github projects.

2023-06-14 15:26 UTC, Loco1982 commented
> I would say our standard tool is Github Projects but we have some legacy tools like clickup, trello etc. If we have a new project we should use github projects.

You're right, made the changes to the text!

2023-06-15 18:53 UTC, tomasdema approved these changes

2023-06-15 21:25 UTC, merged